### ISSUE TITLE
Buildozer refuses to build

### ISSUE THREAD

**Issue by lucasmartins19** [Blackysh/ffmpeg-kit-python#1]
Hi! Im the guy from the youtube video comments. Im attaching the log as you requested. Thanks
[buildozer.log](https://github.com/Blackysh/ffmpeg-kit-python/files/11433333/buildozer.log)

**Comment by arqies** [comment]
You need to change the min_sdk/min_api version in buildozer.conf to 25 or higher. I don't remember what exactly it is called but it is the minimum required version of android api required to run. With android api 25, its should work on devices newer than android 7.1

(If you get further errors, reply here. Once it works, remind me to close the issue)

**Comment by lucasmartins19** [comment]
It worked. For those who might have this problem in the future, the precise option is: "android.minapi". I changed it to 25 and done.
I think would be nice if you added this in the "mini-tutorial" u provided in the page, since the option that causes this error comes incompatible by default with the buildozer init command. 
Thank you for the help!

**Comment by arqies** [comment]
Welcome. I will add the step in modifing buildozer file. Also make sure to use (LINK BELOW) flag if you are getting low quality video exports. 

https://github.com/Blackysh/ffmpeg-kit-python#note-if-you-are-having-lower-quality-exports-add--qv-1--qa-1-before-your-output-filepath-1-for-highest
